### PR TITLE
feat: cherry picked modules

### LINKED ISSUE #7: Support imports containing slashes
Hi Steven,

Currently, if `lodash` is a dependency, this plugin considers `import _ from 'lodash'` as external but not `import fp from 'lodash/fp'`.

It would work if you were to replace: 

https://github.com/stevenbenisek/rollup-plugin-auto-external/blob/c320b49658ea7480a25fcf99c6f84fa36e5bd730/index.js#L37-L46

by:

```javascript
external = id => {
  if (
    (typeof opts.external === "function" && opts.external(id)) ||
    (Array.isArray(opts.external) && opts.external.includes(id))
  ) {
    return true;
  }

  const packageName = id.split("/")[0];

  return ids.includes(packageName);
};
```

I wanted to make a PR to propose this addition but it requires changing most of the test suite because the `external` option would always be a function.
Do you agree that `import fp from 'lodash/fp'` should be considered external too?
If I submit the PR, would you consider merging it?

Thanks

### PR DESCRIPTION
**Pull request by stevenbenisek**
:sparkles: Add support for cherry picked modules (eg: `import _merge from 'lodash/merge';`)
:white_check_mark: Replace unit tests with integration tests
:arrow_up: Update dependencies

Resolves #7

### CODE REVIEW

**Comment by stevenbenisek** [comment]
This will be a major version upgrade. Although the API doesn't change, some people might rely on the old behaviour of cherry-picked modules not being external by default.

**Comment by NathanielHill** [comment]
Does this also work with scoped packages once it's released?

**Comment by stevenbenisek** [comment]
Yes, this will work with scoped packages 😄

**Comment by stevenbenisek** [comment]
@NathanielHill there's an alpha release available if your interested in giving it a go: 

```
npm install rollup-plugin-auto-external@alpha
```

**Pull request merged**
